=== GuillaumeCerdan/editorPlugin/thelia/core/lib/Thelia/Module/schema/module/module-2_1.xsd
<?xml version="1.0" encoding='UTF-8'?>
<xs:schema
        xmlns="http://thelia.net/schema/dic/module"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://thelia.net/schema/dic/module"
        attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        >

    <xs:element name="module">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" minOccurs="1" name="fullnamespace">
                    <xs:annotation>
                        <xs:documentation>The full namespace for the main class module (for example MyModule\MyModule)</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="descriptive" minOccurs="1" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>Complete description, each description must be identify by ISO CODE 639</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="title" minOccurs="1" maxOccurs="1"/>
                            <xs:element type="xs:string" name="subtitle" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="description" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="postscriptum" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="locale"/>
                    </xs:complexType>
                </xs:element>
                <xs:element type="xs:string" minOccurs="0" maxOccurs="1" name="logo">
                    <xs:annotation>
                        <xs:documentation>The path to the logo of the module (for example myModule.png). The recommended size is 128x128.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element type="xs:string" minOccurs="0" maxOccurs="1" name="images-folder">
                    <xs:annotation>
                        <xs:documentation>The folder that contains the images to deploy.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="languages">
                    <xs:annotation>
                        <xs:documentation>Module languages supported : fr_FR, en_US, ...</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="language" minOccurs="1" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z]{2}_[A-Z]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element type="xs:string" name="version">
                    <xs:annotation>
                        <xs:documentation>Module version</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="author">
                    <xs:annotation>
                        <xs:documentation>Module author</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name" minOccurs="1" maxOccurs="1"/>
                            <xs:element type="xs:string" name="company" minOccurs="0" maxOccurs="1"/>
                            <xs:element type="xs:string" name="email" minOccurs="1" maxOccurs="1"/>
                            <xs:element type="xs:anyURI" name="website" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="type">
                    <xs:annotation>
                        <xs:documentation>module type : classic, delivery, payment, ...</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="classic"/>
                            <xs:enumeration value="delivery"/>
                            <xs:enumeration value="payment"/>
                            <xs:enumeration value="marketplace"/>
                            <xs:enumeration value="price"/>
                            <xs:enumeration value="accounting"/>
                            <xs:enumeration value="seo"/>
                            <xs:enumeration value="administration"/>
                            <xs:enumeration value="statistic"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="tags" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Module tags</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="tag" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="required" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>Plugins that should be presents. Plugins are identified by their codes and an optional minimal version</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="module" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="version" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="thelia" minOccurs="0" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>minimum required version of Thelia in 'dot' format (for example 1.2.3.4)</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="stability">
                    <xs:annotation>
                        <xs:documentation>current module stability: alpha, beta, rc, prod</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="alpha"/>
                            <xs:enumeration value="beta"/>
                            <xs:enumeration value="rc"/>
                            <xs:enumeration value="prod"/>
                            <xs:enumeration value="other"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element type="xs:string" name="documentation" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>The name of the directory containing te documentation.</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element type="xs:anyURI" name="urlmiseajour" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>URL to test if a new version of the module exists. Will be called with two get parameters : module name, current version</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element type="xs:anyURI" name="updateurl" minOccurs="0" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>URL to test if a new version of the module exists. Will be called with two get parameters : module name, current version</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GuillaumeCerdan/editorPlugin/thelia/local/modules/AttributeType/Config/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://thelia.net/schema/dic/module"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/module http://thelia.net/schema/dic/module/module-2_1.xsd">
    <fullnamespace>AttributeType\AttributeType</fullnamespace>
    <descriptive locale="en_US">
        <title>Attribute type</title>
        <description>Allows managing the attribute types, eg color, weight ...</description>
    </descriptive>
    <descriptive locale="fr_FR">
        <title>Type de déclinaison</title>
        <description>Permet de gérer des types de déclinaison, exemple : couleur, poid ...</description>
    </descriptive>
    <!-- <logo></logo> -->
    <languages>
        <language>en_US</language>
        <language>fr_FR</language>
    </languages>
    <version>1.2.3</version>
    <author>
        <name>Gilles Bourgeat</name>
        <email>gilles.bourgeat@gmail.com</email>
        <website>https://github.com/gillesbourgeat</website>
    </author>
    <type>classic</type>
    <thelia>2.1.0</thelia>
    <stability>prod</stability>
</module>
